<?php
$this->headTitle('Sign in');

$this->mainMenu()->setActiveItemId('login');

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>$this->translate('Email address'),
    'required' => true,
    'autofocus' => true
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>$this->translate('Password'),
    'required' => true,
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
?>

<div class="row">
    <div class="col-md-offset-4 col-md-3">
        <form class="form-signin" method="post">
            <h2 class="form-signin-heading">
                <?= $this->translate('Please sign in') ?>
            </h2>
            <?php if ($isLoginError): ?>
            <div class="alert alert-warning" role="alert">
               <?= $this->translate('Incorrect login and/or password.') ?> 
                <a href="<?= $this->url('reset-password') ?>">
                <?= $this->translate('Forgot password?') ?></a>
            </div>
            <?php endif; ?>
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
<!--            <div class="checkbox">
                <label>
                    <= $this->formElement($form->get('remember_me')); ?> Remember me
                </label>
            </div>-->
            <br>
            <?= $this->formElement($form->get('redirect_url')); ?>
            <?= $this->formElement($form->get('csrf')) ?>
            <button class="btn btn-lg btn-primary btn-block" type="submit">
                <?= $this->translate('Sign in') ?>
            </button>
        </form>
        <br>
        <a href="<?php echo $this->url('registration'); ?>"><?= $this->translate('User Registration') ?></a> |
        <a href="<?php echo $this->url('reset-password', ['action'=>'resetPassword']); ?>">
            <?= $this->translate('Forgot Password') ?>
        </a>
          
    </div>
</div>
