<?php
$this->headTitle($this->translate('Thank You'));
?>

<div class="row">
<div class="col-md-offset-4 col-md-5">
<h1><?= $this->translate('Reset Password') ?></h1>

<?php if ($id=='sent'): ?>
<p>
    <?= $this->translate('A password reset link has been sent to your email address.') ?>
</p>
<?php elseif ($id=='invalid-email'): ?>
<p>
    <?= $this->translate('There is no user with such an email.') ?>
</p>
<?php elseif ($id=='set'): ?>
<p>
    <?= $this->translate('Your new password has been set successfully.') ?>
</p>
<p>
    <?= $this->translate('Return to') ?> <a href="<?= $this->url('login'); ?>"><?= $this->translate('login page') ?></a>.
</p>
<?php elseif ($id=='failed'): ?>

    <?= $this->translate('Invalid reset key or it may have expired. Please return') ?> 
    <a href="<?= $this->url('reset-password') ?>"><?= $this->translate('here') ?></a> <?= $this->translate('and try reset your password again.') ?>
</p>
<?php endif; ?>
</div>
</div>    