<?php
$this->headTitle($this->translate('Reset Password'));

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>$this->translate('Email address')
    ]);

$form->get('submit')->setAttributes([
    'class'=>'btn btn-large btn-primary', 
    'value'=>$this->translate('Reset Password')]);

$form->prepare();
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($form); ?>

        <h2><?= $this->translate('Reset Password') ?></h2>

        <p><?= $this->translate('Enter your e-mail address below to reset your password') ?></p>

        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>                              

        <?= $this->formElement($form->get('captcha')); ?>
        <p class="hint"><?= $this->translate('Enter the letters above as you see them.') ?></p>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
