<?php
$this->headTitle($this->translate('Add Post'));
$this->mainMenu()->setActiveItemId('posts');
$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
            $this->translate('Posts')=>$this->url('posts'),    
            $this->translate('Add Post')=>''
            ]);
$form = $this->form;
$form->get('title')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>$this->translate('Enter post title here'),
    'label'=>$this->translate('Title')     
    ]);
$form->get('content')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>$this->translate('Type content here'),
    'label'=>$this->translate('Content'),
    'rows'=>6
    ]);
$form->get('tags')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>$this->translate('comma, separated, list, of, tags'),
    'label'=>$this->translate('Tags') 
    ]);
$form->get('status')->setAttributes([
    'class'=>'form-control', 
    'label'=>$this->translate('Status')    
    ]);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 
    'value'=>$this->translate('Next Step')]);
$form->prepare();
?>

<h1><?= $this->translate('Add Post - Step 1') ?></h1>

<p>
    <?= $this->translate('Please fill out the following form and click the *Next Step* button.') ?>
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('title')); ?>
            <?= $this->formElement($form->get('title')); ?>
            <?= $this->formElementErrors($form->get('title')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('content')); ?>
            <?= $this->formElement($form->get('content')); ?>
            <?= $this->formElementErrors($form->get('content')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('tags')); ?>
            <?= $this->formElement($form->get('tags')); ?>
            <?= $this->formElementErrors($form->get('tags')); ?>                  
            <p class="help-block"><?= $this->translate('Separate tags with comma.') ?></p>
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>                  
        </div>
                
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   
