<?php
$this->headTitle($this->translate('Add Post'));
$this->mainMenu()->setActiveItemId('posts');
$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
            $this->translate('Posts')=>$this->url('posts'),    
            $this->translate('Add Post')=>''
            ]);
$form = $this->form;
$form->get('file')->setAttributes([
    'label'=>$this->translate('Image file')     
    ]);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->get('submit')->setValue($this->translate('Continue'));

$form->prepare();

?>



<h1><?= $this->translate('Add Post - Step 2') ?></h1>



<p>

    <?= $this->translate('Please fill out the following form and press the') ?>
     <i><?= $this->translate('Continue') ?></i> 
    <?= $this->translate('button.  To finish, do not select files.  Resize to square if photos appear sideways.') ?>  
</p>



<div class="row">

    <div class="col-md-6">

        <?= $this->form()->openTag($form); ?>

        

        <div class="form-group">

            <?= $this->formLabel($form->get('file')); ?>

            <?= $this->formElement($form->get('file')); ?>

            <?= $this->formElementErrors($form->get('file')); ?>

            <div class="hint"><?= $this->translate('PNG and JPG formats are allowed') ?></div>

        </div>

                

        <?= $this->formElement($form->get('submit')); ?>

        

        <?= $this->form()->closeTag(); ?>

    </div>    

</div>    

<hr/>



<?php if(count($files)==0): ?>



<p>

    <i><?= $this->translate('There are no images to display.') ?></i>

</p>



<?php else: ?>



<div class="row">

    <div class="col-sm-6 col-md-12">



        <?php foreach($files as $file): ?>  


        <div class="img-thumbnail">

            

            <img src="<?= $this->url('images', ['action'=>'addFile'], 

                    ['query'=>['name'=>$file, 'id'=>$user->getId(),  
                        'thumbnail'=>true]]); ?>">

            

            <div class="caption">

                <br>
                
                 <span>
                    
                     <a href="<?= $this->url('images',  

                            ['action'=>'removeAddTemp'], ['query'=>['name'=>$file, 
                                'id'=>$user->getId()]]); ?>" 

                            class="btn btn-default" role="button">Remove</a>
                            
                </span>
                
                <span>            

                    <a target="_blank" href="<?= $this->url('images',  

                            ['action'=>'addFile'], ['query'=>['name'=>$file, 
                                'id'=>$user->getId()]]); ?>" 

                            class="btn btn-default" role="button">View</a>

                </span>

            </div>

        </div>



        <?php endforeach; ?>

    </div>

</div>






<?php endif; ?>