<?php
$this->headTitle($this->translate('Add Post'));
$this->mainMenu()->setActiveItemId('posts');
$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
            $this->translate('Posts')=>$this->url('posts'),    
            $this->translate('Add Post')=>''
            ]);
$form = $this->form;
$form->get('audio')->setAttributes([
    'label'=>$this->translate('Audio file')     
    ]);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->get('submit')->setValue($this->translate('Continue'));

$form->prepare();

?>



<h1><?= $this->translate('Add Post - Step 4') ?></h1>


<p>

    <?= $this->translate('Please fill out the following form and press the') ?>
     <i><?= $this->translate('Continue') ?></i> 
    <?= $this->translate('button.  To finish, do not select a file.') ?>  

</p>



<div class="row">

    <div class="col-md-6">

        <?= $this->form()->openTag($form); ?>

        

        <div class="form-group">

            <?= $this->formLabel($form->get('audio')); ?>

            <?= $this->formElement($form->get('audio')); ?>

            <?= $this->formElementErrors($form->get('audio')); ?>

            <div class="hint"><?= $this->translate('(MP3, OGG and M4A formats are allowed)') ?></div>

        </div>

                

        <?= $this->formElement($form->get('submit')); ?>

        

        <?= $this->form()->closeTag(); ?>

    </div>    

</div>    

<hr/>



<?php if(count($files)==0): ?>



<p>

    <i><?= $this->translate('There is no audio file to display.') ?></i>

</p>



<?php else: ?>



<div class="row">

    <div class="col-sm-6 col-md-12">



        <?php foreach($files as $file): ?>  



        <div class="img-thumbnail">
                        
            <audio controls>
                <source src="/audio/user/<?= $user->getId()?>/<?= $file ?>" >
            <?= $this->translate('Your browser does not support the audio tag.') ?>
            </audio>             

            <div class="caption">

                                
                <br>
                
                 <span>

                    <a href="<?= $this->url('audio',  
                            ['action'=>'removeAddTemp'], ['query'=>['name'=>$file, 
                                'id'=>$user->getId()]]); ?>" 

                            class="btn btn-default" role="button"><?= $this->translate('Remove') ?></a>

                </span>
                
            </div>

        </div>



        <?php endforeach; ?>

    </div>

</div>






<?php endif; ?>