<?php
$this->headTitle('Add Post');
$this->mainMenu()->setActiveItemId('posts');
$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Posts'=>$this->url('posts'),    
            'Add Post'=>''
            ]);
$form = $this->form;

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->get('submit')->setValue('Continue');

$form->prepare();

?>



<h1>Add Post - Step 4</h1>



<p>

    Please fill out the following form and press the <i>Continue</i> button.  
    To finish, do not select files.

</p>



<div class="row">

    <div class="col-md-6">

        <?= $this->form()->openTag($form); ?>

        

        <div class="form-group">

            <?= $this->formLabel($form->get('audio')); ?>

            <?= $this->formElement($form->get('audio')); ?>

            <?= $this->formElementErrors($form->get('audio')); ?>

            <div class="hint">(MP3 and OGG formats are allowed)</div>

        </div>

                

        <?= $this->formElement($form->get('submit')); ?>

        

        <?= $this->form()->closeTag(); ?>

    </div>    

</div>    

<hr/>



<?php if(count($files)==0): ?>



<p>

    <i>There are no files to display.</i>

</p>



<?php else: ?>



<div class="row">

    <div class="col-sm-6 col-md-12">



        <?php foreach($files as $file): ?>  



        <div class="img-thumbnail">
                        
            <audio controls>
                <source src="/audio/user/<?= $user->getId()?>/<?= $file ?>" >
            Your browser does not support the audio tag.
            </audio>             

            <div class="caption">

                                
                <br>
                
                 <span>

                    <a href="<?= $this->url('audio',  
                            ['action'=>'removeAddTemp'], ['query'=>['name'=>$file, 
                                'id'=>$user->getId()]]); ?>" 

                            class="btn btn-default" role="button">Remove</a>

                </span>
                
            </div>

        </div>



        <?php endforeach; ?>

    </div>

</div>






<?php endif; ?>