<?php
$this->headTitle($this->translate('Manage Posts'));
$this->mainMenu()->setActiveItemId('posts');
$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
            $this->translate('Posts')=>$this->url('posts'),
            ]);
?>

<h1><?= $this->translate('Manage My Posts') ?></h1>

<p>
<a class="btn btn-default" href="
    <?= $this->url('posts', ['action'=>'add']); ?>">
    <?= $this->translate('New Post') ?>
</a>
</p>

<table class="table table-striped">

   <tr>
        <th><?= $this->translate('ID') ?></th>
        <th><?= $this->translate('Post Title') ?></th>
        <th><?= $this->translate('Image') ?></th>
        <th><?= $this->translate('Date Created') ?></th>
        <th><?= $this->translate('Status') ?></th> 
        <th><?= $this->translate('Actions') ?></th>        
    </tr>
    
    <?php foreach ($posts as $post): ?>
    
    <tr>
        <td><?= $this->escapeHtml($post->getId()); ?></td>
        <td>
            <a href="<?= $this->url('posts', ['action'=>'view', 'id'=>$post->getId()]); ?>">
                <?= $this->escapeHtml($post->getTitle()); ?>
            </a> 
        </td>
        <td>
            
            <?php 
    $files = $imageManager->getFirstSavedFiles($post, 1);
    ?>
    

    <?php if(count($files)==0): ?>

    <p>
      <i><?= $this->translate('There is no image to display.') ?></i>
    </p>

    <?php else: ?>

    

        <?php foreach($files as $title => $file): ?> 
            <h3><?= $title ?></h3>
            <a target="_blank" href="<?= $file ?>" class="btn btn-default" role="button">             
                <img width="240" src="<?= $file ?>">    
            </a>
        <?php endforeach; ?>
    

    <?php endif; ?>      
        </td>
              
        <td><?= $this->escapeHtml($postManager->getPostDateAsString($post) 
                .' '. date('H:i:s', strtotime($post->getDateCreated()))); ?>&nbsp;UTC</td>
        <td><?= $this->escapeHtml($postManager->getPostStatusAsString($post)); ?></td>        
        <td>
            <a class="btn btn-info" href="<?= $this->url('posts', 
                    ['action'=>'edit', 'id'=>$post->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span>&nbsp;<?= $this->translate('Edit') ?> 
            </a>
            <a class="btn btn-danger" href="<?= $this->url('posts',
                    ['action'=>'delete', 'id'=>$post->getId()]); ?>">
                <span class="glyphicon glyphicon-remove"></span>&nbsp;<?= $this->translate('Delete') ?> 
            </a>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>

<?= $this->paginationControl($posts,
                    'Sliding',
                    'application/partial/paginator', 
                    array('route' => 'posts')); ?>