<?php
$this->headTitle('Manage Posts');
$this->mainMenu()->setActiveItemId('posts');
$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Posts'=>$this->url('posts'),
            ]);
?>

<h1>Manage My Posts</h1>

<p>
<a class="btn btn-default" href="
    <?= $this->url('posts', ['action'=>'add']); ?>">
    New Post
</a>
</p>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Post Title</th>
        <th>Image</th>
        <th>Date Created</th>
        <th>Status</th> 
        <th>Actions</th>        
    </tr>
    
    <?php foreach ($posts as $post): ?>
    
    <tr>
        <td><?= $this->escapeHtml($post->getId()); ?></td>
        <td>
            <a href="<?= $this->url('posts', ['action'=>'view', 'id'=>$post->getId()]); ?>">
                <?= $this->escapeHtml($post->getTitle()); ?>
            </a> 
        </td>
        <td>
            
            <?php 
    $files = $imageManager->getFirstSavedFiles($post->getId(), 1);
    ?>
    

    <?php if(count($files)==0): ?>

    <p>
      <i>There is no image to display.</i>
    </p>

    <?php else: ?>

    

        <?php foreach($files as $file): ?>  
            <a target="_blank" href="<?= $this->url('images', ['action' => 'file'], 
            ['query' => ['name' => $file, 'id' => $post->getId(), 
            'loc' => 'perm']]); ?>" class="btn btn-default" role="button"> 

                <img src="<?= $this->url('images', ['action' => 'file'], ['query' => 
                ['name' => $file, 'id' => $post->getId(), 'loc' => 'perm', 
                'thumbnail' => true]]); ?>">

            </a>
        <?php endforeach; ?>
    

    <?php endif; ?>

    
            
        </td>
        <td><?= $this->escapeHtml($post->getDateCreated()); ?></td>
        <td><?= $this->escapeHtml($postManager->getPostStatusAsString($post)); ?></td>        
        <td>
            <a class="btn btn-info" href="<?= $this->url('posts', 
                    ['action'=>'edit', 'id'=>$post->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edit
            </a>
            <a class="btn btn-danger" href="<?= $this->url('posts',
                    ['action'=>'delete', 'id'=>$post->getId()]); ?>">
                <span class="glyphicon glyphicon-remove"></span> Delete
            </a>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>

<?= $this->paginationControl($posts,
                    'Sliding',
                    'application/partial/paginator', 
                    array('route' => 'posts')); ?>