<?php
$this->headTitle($this->translate('Edit Post'));
$this->mainMenu()->setActiveItemId('posts');
$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
            $this->translate('Posts')=>$this->url('posts'),    
            $this->translate('Edit Post')=>''
            ]);
$form = $this->form;
$form->get('file_title')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>$this->translate('Enter image title here'),
    'label'=>$this->translate('Image title')     
    ]);
$form->get('file')->setAttributes([
    'label'=>$this->translate('Image files')     
    ]);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->get('submit')->setValue($this->translate('Continue'));

$form->prepare();

?>



<h1><?= $this->translate('Edit Post - Step 2') ?></h1>



<p>

    <?= $this->translate('Please fill out the following form and press the') ?>
     <i><?= $this->translate('Continue') ?></i> 
    <?= $this->translate('button.  To finish, do not select files.  Resize to square if photos appear sideways.') ?>  
</p>



<div class="row">

    <div class="col-md-6">

        <?= $this->form()->openTag($form); ?>

        <div class="form-group">

            <?= $this->formLabel($form->get('file')); ?>

            <?= $this->formElement($form->get('file')); ?>

            <?= $this->formElementErrors($form->get('file')); ?>

            <div class="hint"><?= $this->translate('(PNG and JPG formats are allowed)') ?></div>

        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('file_title')); ?>
            
            <?= $this->formElement($form->get('file_title')); ?>
            
            <?= $this->formElementErrors($form->get('file_title')); ?>                  
        </div>

                

        <?= $this->formElement($form->get('submit')); ?>

        

        <?= $this->form()->closeTag(); ?>

    </div>    

</div>   

<hr/>



<?php if(count($files)==0): ?>



<p>

    <i><?= $this->translate('There are no images to display.') ?></i>

</p>



<?php else: ?>



<div class="row">

    <div class="col-sm-6 col-md-12">



        <?php foreach($files as $name => $file): ?>  



        <div class="img-thumbnail">

            

            <img src="<?= $this->url('images', ['action'=>'file'], 

                    ['query'=>['name'=>$file, 'id'=>$post->getId(),  
                        'thumbnail'=>true]]); ?>">

            

            <div class="caption">

                <h3><?php echo $fileTitles[$name]; ?></h3> 
       
                <br>
                
                 <span>

                    <a href="<?= $this->url('images',  
                            ['action'=>'removeTemp'], ['query'=>['name'=>$file, 
                                'id'=>$post->getId()]]); ?>" 

                            class="btn btn-default" role="button"><?= $this->translate('Remove') ?></a>

                </span>
                
                <span>

                    <a target="_blank" href="<?= $this->url('images',  

                            ['action'=>'file'], ['query'=>['name'=>$file, 
                                'id'=>$post->getId()]]); ?>" 

                            class="btn btn-default" role="button"><?= $this->translate('View') ?></a>

                </span>

            </div>

        </div>



        <?php endforeach; ?>

    </div>

</div>






<?php endif; ?>