<?php
$this->headTitle('View Post - ' . $post->getTitle());
$this->mainMenu()->setActiveItemId('posts');
$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Posts'=>$this->url('posts'),
            'View Post'=>''
            ]);
        
$form = $this->form;
$form->get('author')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Author\'s name'
    ]);
$form->get('comment')->setAttributes([
    'class'=>'form-control',
    'rows'=>6, 
    'placeholder'=>'Text'
    ]);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();        
?>

<a href="
    <?= $this->url('blog', ['action'=>'index']); ?>">
    &lt;&lt; Back to list of posts
</a>

<h1>
    <?= $this->escapeHtml($post->getTitle()); ?>    
</h1>

<p class="comments-header">
    <?= $this->escapeHtml($postManager->getResponseCountStr($post)); ?> | 
    <a href="#response">
        Add new response
    </a>
</p>

<p>
    Published: <?= $this->escapeHtml(date('jS \of F Y', strtotime($post->getDateCreated()))); ?> 
    | Tags: <?= $this->escapeHtml($postManager->convertTagsToString($post)); ?>   
</p>

<p>    
    <?= $this->escapeHtml($post->getContent()); ?>
</p>

<hr/>

<?php if(count($files)==0): ?>

<p>
  <i>There are no images to display.</i>
</p>

<?php else: ?>

<div class="row">
  <div class="col-sm-6 col-md-12">

    <?php foreach($files as $file): ?>  
        <a target="_blank" href="<?= $this->url('images', ['action' => 'file'], 
        ['query' => ['name' => $file, 'id' => $post->getId(), 
        'loc' => 'perm']]); ?>" class="btn btn-default" role="button"> 
            
            <img src="<?= $this->url('images', ['action' => 'file'], ['query' => 
            ['name' => $file, 'id' => $post->getId(), 'loc' => 'perm', 
            'thumbnail' => true]]); ?>">
            
        </a>
    <?php endforeach; ?>
  </div>
</div>

<?php endif; ?>

<hr/>

<h3><?= $this->escapeHtml($postManager->getResponseCountStr($post)); ?></h3>

<?php foreach ($post->getComments() as $comment): ?>

<hr>

<p>
    <?= $this->escapeHtml($comment->getAuthor()) ?> on 
    <?= $this->escapeHtml($comment->getDateCreated()); ?>
</p>

<p>
    <?= $this->escapeHtml($comment->getContent()); ?>    
</p>

<?php endforeach; ?>

<hr>

<a name="response"></a>


<p>
<a class="btn btn-default" href="
    <?= $this->url('posts', ['action'=>'add'], ['query' => 
                ['id' => $post->getId()]]); ?>">
    Leave Response
</a>
</p>
