<?php
$this->headTitle($post->getTitle());
$this->headMeta()->appendName('description', $post->getDescription());
$this->headMeta()->appendName('author', $post->getUser()->getFullName());
$this->headMeta()->appendName('keywords', $postManager->convertTagsToString($post));
$this->mainMenu()->setActiveItemId('posts');
$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
            $this->translate('Posts')=>$this->url('posts'),
            $this->translate('View Post')=>''
            ]);
?>

<a href="
    <?= $this->url('blog', ['action'=>'index']); ?>">
    &larr; <?= $this->translate('To blog') ?>
</a>

<h1>
    <?= $this->escapeHtml($post->getTitle()); ?>    
</h1>

<p>
    <b><?= $this->translate('Published:') ?></b> <?= $this->escapeHtml($postManager->getPostDateAsString($post)); ?> 
    | <b><?= $this->translate('Tags:') ?></b> <?= $this->escapeHtml($postManager->convertTagsToString($post)); ?>   
</p>

    <?php
        
    $country = $post->getGeography()->getCountryName();
    $translatedCountry = $this->translate($country);
    $region = $post->getGeography()->getRegion();
    $translatedRegion = $this->translate($region);
    $city = $post->getGeography()->getCity();
    $translatedCity = $this->translate($city);

    ?>

 <p>
    <b><?= $this->translate('Country:') ?></b> <?= $this->escapeHtml($translatedCountry); ?> 
    | <b><?= $this->translate('Region:') ?></b> <?= $this->escapeHtml($translatedRegion); ?>  
    | <b><?= $this->translate('City:') ?></b> <?= $this->escapeHtml($translatedCity); ?>  
</p> 

 <p>
    <b><?= $this->translate('Author:') ?></b> <a href="<?= $this->url('blog', ['action'=>'index', 'user'=>$post->getUser()->getId()]); ?>">                   
        
                    <span >
                        <?= $this->escapeHtml($post->getUser()->getFullName()); ?> 
                    </span>
                
                </a>     
</p> 

<p class="responses-header">
    <b><?= $this->escapeHtml($responseCountString); ?></b> | 
    <a href="<?= $this->url('posts', ['action'=>'add'], ['query' => 
                    ['id' => $post->getId()]]); ?>">
        <?= $this->translate('Add new response') ?>
    </a>
</p>

<?php
$parentPosts = $post->getParentPosts();
foreach ($parentPosts as $parent):
    ?>
    <p><b><?= $this->translate('Response to:') ?></b><a href="<?= $this->url('posts', ['action' => 'view', 'id' => $parent->getId()]); ?>">
            <?= $this->escapeHtml($parent->getTitle()); ?>
        </a>   
    </p>
<?php endforeach; 
if(count($parentPosts)<1)
    echo $this->translate('<p><b>Response to:</b> None');
?>
    
<p>    
    <b><?= $this->translate('Description:') ?></b>
</p>

<p>    
    <?= nl2br($this->escapeHtml($post->getDescription())) ?>
</p>

<p>    
    <b><?= $this->translate('Content:') ?></b>
</p>

<p>    
    <?= nl2br($this->escapeHtml($post->getContent())) ?>
</p>

<hr/>

<?php if(count($files)==0): ?>

<p>
  <i><?= $this->translate('There are no images to display.') ?></i>
</p>

<?php else: ?>

<div class="row">
  <div class="col-sm-6 col-md-12">

    <?php foreach($files as $file): ?> 
        <a target="_blank" href="<?= $file['url'] ?>" class="btn btn-default" role="button">             
            <img width="240" alt="<?= $file['title'] ?>" title="<?= $file['title'] ?>" src="<?= $file['url'] ?>">    
        </a>
             
    <?php endforeach; ?>
  </div>
</div>

<?php endif; ?>

<hr/>

<?php if(count($videos)==0): ?>

<p>
  <i><?= $this->translate('There is no video to display.') ?></i>
</p>

<?php else: ?>

<div class="row">
  <div class="col-sm-6 col-md-12">

    <?php foreach($videos as $video): ?>  
        <div class="img-thumbnail">
                        
            <video width="320" height="240" controls>
                <source src="<?= $video ?>" >
            <?= $this->translate('Your browser does not support the video tag.') ?>
            </video>             

        </div>
    <?php endforeach; ?>
  </div>
</div>

<?php endif; ?>

<hr/>

<?php if(count($audioFiles)==0): ?>

<p>
   <i><?= $this->translate('There is no audio file to display.') ?></i>
</p>

<?php else: ?>

<div class="row">
  <div class="col-sm-6 col-md-12">

    <?php foreach($audioFiles as $audio): ?>  
        <div class="img-thumbnail">
                        
            <audio controls>
                <source src="<?= $audio ?>" >
            <?= $this->translate('Your browser does not support the audio tag.') ?>
            </audio>             

        </div>
    <?php endforeach; ?>
  </div>
</div>

<?php endif; ?>

<hr/>

<a name="response"></a>
    

<div class="row">
    <div class="col-md-8">
    <p>
    <a class="btn btn-default" href="
        <?= $this->url('posts', ['action'=>'add'], ['query' => 
                    ['id' => $post->getId()]]); ?>">
        <?= $this->translate('Leave Response') ?>
    </a>
    </p>
    </div>
</div> 


<h3><?= $this->escapeHtml($responseCountString); ?></h3>



    <?php foreach($posts as $childPost): ?>
        
    <h3>
        <a href="<?= $this->url('posts', ['action'=>'view', 'id'=>$childPost->getId()]); ?>">
            <?= $this->escapeHtml($childPost->getTitle()); ?>
        </a>    
    </h3>
    
    <p>
        <b><?= $this->translate('Published:') ?></b> <?= $this->escapeHtml($postManager->getPostDateAsString($childPost)); ?> 
        | <b><?= $this->translate('Tags:') ?></b> <?= $this->escapeHtml($postManager->convertTagsToString($childPost)); ?>   
    </p>    
        
    <p class="responses-header">
        <b><?= $this->escapeHtml($postManager->getResponseCountStr($childPost)); ?></b> | 
        <a href="<?= $this->url('posts', ['action'=>'view', 'id'=>$childPost->getId()],
                ['fragment'=>'response']); ?>">
            <?= $this->translate('Add new response') ?>
        </a>
    </p>
    
    <p>    
        <b><?= $this->translate('Description:') ?></b>
    </p>
    
    <p>    
        <?= substr(nl2br($this->escapeHtml($childPost->getDescription())), 0, 500) ?> &hellip;
    </p>
    
    <?php 
    $childFiles = $imageManager->getFirstSavedFiles($childPost);
    ?>
    
    <hr/>

    <?php if(count($childFiles)==0): ?>

    <p>
      <i><?= $this->translate('There are no images to display.') ?></i>
    </p>

    <?php else: ?>

    <div class="row">
      <div class="col-sm-6 col-md-12">

        <?php foreach($childFiles as $childFile): ?>
            <a target="_blank" href="<?= $childFile['url'] ?>" class="btn btn-default" role="button">             
            <img width="240" alt="<?= $childFile['title'] ?>" title="<?= $childFile['title'] ?>" src="<?= $childFile['url'] ?>">    
        </a>
        <?php endforeach; ?>
      </div>
    </div>

    <?php endif; ?>

    <hr/>

    <?php endforeach; ?>

    <?= $this->paginationControl($posts,
                    'Sliding',
                    'application/partial/paginator', 
                    array('route' => 'blog')); ?>
   