<?php
$this->headTitle($this->translate('Account Status'));

$this->mainMenu()->setActiveItemId('settings');

$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
            $this->translate('Settings')=>$this->url('settings'),
            $this->translate('Account Status') => $this->url('settings', ['action' => 'accountStatus']),
            ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-danger', 
    'value'=>$this->translate('Submit')]);

$form->prepare();
?>

<a href="
    <?= $this->url('settings'); ?>">
    &larr; <?= $this->translate('To settings menu') ?>
</a>

<h1><?= $this->translate('Settings') ?></h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
        <?= $this->formElement($form->get('submit')); ?>
        </div>
        
        <div class="hint"><?= $this->translate('Warning:  All of your posts and your account will be deleted.') ?></div>
        
        <?= $this->formElement($form->get('csrf')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   
