<?php
$this->headTitle($this->translate('Email'));

$this->mainMenu()->setActiveItemId('settings');

$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
            $this->translate('Settings')=>$this->url('settings'),
            $this->translate('Email') => $this->url('settings', ['action' => 'email']),
            ]);

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>$this->translate('name@example.com')
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 
    'value'=>$this->translate('Submit')]);

$form->prepare();
?>

<h1><?= $this->translate('Settings') ?></h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>                              
        </div>
        
        <div class="form-group">
        <?= $this->formElement($form->get('submit')); ?>
        </div>
        
        <?= $this->formElement($form->get('csrf')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   
