<?php
$this->headTitle('Settings');

$this->mainMenu()->setActiveItemId('settings');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Settings'=>$this->url('settings'),
            ]);
?>

<h2>Settings</h2>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></td>
                <td></td>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($user->getDateCreated()) ?>&nbsp;UTC</td>
                <td></td>
            </tr>
            <tr>
                <th>Full Name:</th>
                <td><?= $this->escapeHtml($user->getFullName()) ?></td>
                <td>
                    <a class="btn btn-info" href="<?php echo 
                        $this->url('settings', ['action' => 'fullName']); ?>">
                        <span class="glyphicon glyphicon-pencil" ></span> Edit
                    </a>
                </td>
            </tr>
            <tr>
                <th>E-mail:</th>
                <td><?= $this->escapeHtml($user->getEmail()) ?></td>
                 <td>
                    <a class="btn btn-info" href="<?php echo 
                        $this->url('settings', ['action' => 'email']); ?>">
                        <span class="glyphicon glyphicon-pencil" ></span> Edit
                    </a>
                </td>
            </tr>
            <tr>
                <th>Language:</th>
                <td><?= $this->escapeHtml($user->getLanguageAsString()) ?></td>
                <td>
                    <a class="btn btn-info" href="<?php echo 
                        $this->url('settings', ['action' => 'language']); ?>">
                        <span class="glyphicon glyphicon-pencil" ></span> Edit
                    </a>
                </td>
            </tr> 
            <tr>
                <th>Password:</th>
                <td></td>
                <td>
                    <a class="btn btn-info" href="<?php echo 
                        $this->url('settings', ['action' => 'password']); ?>">
                        <span class="glyphicon glyphicon-pencil" ></span> Edit
                    </a>
                </td>
            </tr>   
            <tr>
                <th>Account Status:</th>
                <td></td>
                <td>
                    <a class="btn btn-info" href="<?php echo 
                        $this->url('settings', ['action' => 'accountStatus']); ?>">
                        <span class="glyphicon glyphicon-pencil" ></span> Edit
                    </a>
                </td>
            </tr>
        </table>
    </div>
</div>