<?php
$this->headTitle($this->translate('Language'));

$this->mainMenu()->setActiveItemId('settings');

$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
            $this->translate('Settings')=>$this->url('settings'),
            $this->translate('Language') => $this->url('settings', ['action' => 'language']),
            ]);

$form->get('language')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 
    'value'=>$this->translate('Submit')]);

$form->prepare();
?>

<h1><?= $this->translate('Settings') ?></h1>

<div class="row">
    <div class="col-md-4">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('language')); ?>
            <?= $this->formElement($form->get('language')); ?>
            <?= $this->formElementErrors($form->get('language')); ?>                              
        </div>
        
        <div class="form-group">
        <?= $this->formElement($form->get('submit')); ?>
        </div>
        
        <?= $this->formElement($form->get('csrf')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   
