<?php
$this->headTitle('Language');

$this->mainMenu()->setActiveItemId('settings');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Settings' => $this->url('settings'),
            'Language' => $this->url('settings', ['action' => 'language']),
            ]);

$form->get('language')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('submit')->setAttributes(array('class'=>'btn btn-primary'));

$form->prepare();
?>

<h1>Settings</h1>

<div class="row">
    <div class="col-md-4">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('language')); ?>
            <?= $this->formElement($form->get('language')); ?>
            <?= $this->formElementErrors($form->get('language')); ?>                              
        </div>
        
        <div class="form-group">
        <?= $this->formElement($form->get('submit')); ?>
        </div>
        
        <?= $this->formElement($form->get('csrf')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   
