<?php
$this->headTitle($this->translate('Thank You'));

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
            $this->translate('Settings')=>$this->url('settings'),
            ]);
?>

<div class="row">
<div class="col-md-5">
<h1><?= $this->translate('Settings') ?></h1>

<?php if ($id=='sent'): ?>
<p>
    <?= $this->translate('An email confirmation link has been sent to your email address.') ?>
</p>

<?php elseif ($id=='confirmed'): ?>
<p>
    <?= $this->translate('Your email has been confirmed successfully.') ?>
</p>
<p>
    <?= $this->translate('Return to') ?> <a href="<?= $this->url('settings'); ?>"><?= $this->translate('settings page') ?></a>.
</p>

<?php elseif ($id=='exists'): ?>
<p>
    <?= $this->translate('A user with that email already exists.') ?>
</p>
<p>
    <?= $this->translate('Please return') ?> <a href="<?= $this->url('settings', ['action'=>'email']); ?>"><?= $this->translate('here') ?></a> 
    <?= $this->translate('and try to update again with a different email.') ?>
</p>

<?php elseif ($id=='failed'): ?>

<p>
    <?= $this->translate('Invalid reset key or it may have expired. Please return') ?> 
    <a href="<?= $this->url('settings', ['action'=>'index']); ?>"><?= $this->translate('here') ?></a> <?= $this->translate('and try to update again.') ?>
</p>

<?php elseif ($id=='passwordUpdated'): ?>

<p>
    <?= $this->translate('Your password has been updated successfully.') ?>
</p>
<p>
    <?= $this->translate('Return to') ?> <a href="<?= $this->url('settings'); ?>"><?= $this->translate('settings page') ?></a>.
</p>
<?php endif; ?>
</div>
</div>   
