<?php
$this->headTitle('Password');

$this->mainMenu()->setActiveItemId('settings');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Settings' => $this->url('settings'),
            'Password' => $this->url('settings', ['action' => 'password']),
            ]);

$form->get('password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Type password here (6 characters at minimum)'
    ]);

$form->get('submit')->setAttributes(array('class'=>'btn btn-primary'));

$form->prepare();
?>

<h1>Settings</h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <?= $this->formElementErrors($form->get('password')); ?>                              
        </div>
        
        <div class="form-group">
        <?= $this->formElement($form->get('submit')); ?>
        </div>
        
        <?= $this->formElement($form->get('csrf')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   
