<?php
$this->headTitle('User Registration');

$this->mainMenu()->setActiveItemId('register');

$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
            $this->translate('User Registration') => $this->url('registration')
            ]);

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>$this->translate('name@example.com'),
    'label'=>$this->translate('Your E-mail')
    ]);

$form->get('full_name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>$this->translate('John Doe'),
    'label'=>$this->translate('Full Name')
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>$this->translate('Type password here (6 characters at minimum)'),
    'label'=>$this->translate('Choose Password') 
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 
    'value'=>$this->translate('Submit')]);

$form->prepare();
?>

<h1><?= $this->translate('User Registration') ?></h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>                              
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('full_name')); ?>
            <?= $this->formElement($form->get('full_name')); ?>
            <?= $this->formElementErrors($form->get('full_name')); ?>                              
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <?= $this->formElementErrors($form->get('password')); ?>                              
        </div>
        
        <div class="form-group">
        <?= $this->formElement($form->get('submit')); ?>
        </div>
        
        <?= $this->formElement($form->get('csrf')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   
