<?php
$this->headTitle($this->translate('Thank You'));

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
            $this->translate('User Registration')=> $this->url('registration')
            ]);
?>

<div class="row">
<div class="col-md-5">
<h1><?= $this->translate('User Registration') ?></h1>

<?php if ($id=='sent'): ?>
<p>
    <?= $this->translate('A registration confirmation link has been sent to your email address.') ?>
</p>

<?php elseif ($id=='confirmed'): ?>
<p>
    <?= $this->translate('Your registration has been confirmed successfully.') ?>
</p>
<p>
    <?= $this->translate('Return to') ?> <a href="<?= $this->url('login'); ?>"><?= $this->translate('login page') ?></a>.
</p>

<?php elseif ($id=='exists'): ?>
<p>
    <?= $this->translate('A user with that email already exists.') ?>
</p>
<p>
    <?= $this->translate('Please return') ?> <a href="<?= $this->url('registration', ['action'=>'index']); ?>"><?= $this->translate('here') ?></a> 
    <?= $this->translate('and try to register again with a different email.') ?>
</p>

<?php elseif ($id=='failed'): ?>

    <?= $this->translate('Invalid reset key or it may have expired. Please return') ?> 
    <a href="<?= $this->url('registration', ['action'=>'index']); ?>"><?= $this->translate('here') ?></a> <?= $this->translate('and try to register again.') ?> 
</p>
<?php endif; ?>
</div>
</div>   
