<?php
$this->headTitle('Blog');
$this->mainMenu()->setActiveItemId('blog');
$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Blog'=>$this->url('blog')
            ]);

$form = $this->form;
$form->setAttribute('action', $this->url('blog'));
$form->get('tags')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'comma, separated, list, of, tags'
    ));
$form->get('country')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'Country Name'
    ));
$form->get('region')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'Region Name'
    ));
$form->get('city')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>'City Name'
    ));
$form->get('submit')->setAttributes(array('class'=>'btn btn-primary'));
$form->prepare();
?>



<div class="row">
    <div class="col-md-6">
        <?php echo $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('tags')); ?>
            <?php echo $this->formElement($form->get('tags')); ?>
            <?php echo $this->formElementErrors($form->get('tags')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('country')); ?>
            <?php echo $this->formElement($form->get('country')); ?>
            <?php echo $this->formElementErrors($form->get('country')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('region')); ?>
            <?php echo $this->formElement($form->get('region')); ?>
            <?php echo $this->formElementErrors($form->get('region')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('city')); ?>
            <?php echo $this->formElement($form->get('city')); ?>
            <?php echo $this->formElementErrors($form->get('city')); ?>                  
        </div>
                
        <?php echo $this->formElement($form->get('csrf')); ?>
        
        <?php echo $this->formElement($form->get('submit')); ?>
        
        <?php echo $this->form()->closeTag(); ?>
    </div>    
</div> 

<?php 

if(
        $form->get('tags')->getValue() == '' &&
        $form->get('country')->getValue() == '' &&
        $form->get('region')->getValue() == '' &&
        $form->get('city')->getValue() == '' &&
        $tagFilter == '' &&
        $userFilter == '' 
  ): 
     
?>

<h1>All Posts</h1>
    
<?php endif; ?>

<div class="row">
    
    <div class="col-md-8">

    <?php foreach($posts as $post): ?>
        
    <h3>
        <a href="<?= $this->url('posts', ['action'=>'view', 'id'=>$post->getId()]); ?>">
            <?= $this->escapeHtml($post->getTitle()); ?>
        </a>    
    </h3>
    
    <p>
        Published: <?= $this->escapeHtml(date('jS \of F Y', strtotime($post->getDateCreated()))); ?> 
        | Tags: <?= $this->escapeHtml($postManager->convertTagsToString($post)); ?>   
    </p> 
    
    <p>
        Country: <?= $this->escapeHtml($post->getGeography()->getCountryName()); ?> 
        | Region: <?= $this->escapeHtml($post->getGeography()->getRegion()); ?>  
        | City: <?= $this->escapeHtml($post->getGeography()->getCity()); ?>  
    </p>  
    
    <p>
    Author: <a href="<?= $this->url('blog', ['action'=>'index', 'user'=>$post->getUser()->getId()]); ?>">                   
        
                    <span >
                        <?= $this->escapeHtml($post->getUser()->getFullName()); ?> 
                    </span>
                
                </a>     
</p> 
        
    <p class="responses-header">
        <?= $this->escapeHtml($postManager->getResponseCountStr($post)); ?> | 
        <a href="<?= $this->url('posts', ['action'=>'add'], ['query' => 
                    ['id' => $post->getId()]]); ?>">
            Add new response
        </a>
    </p>
    
    <?php
    $parentPosts = $post->getParentPosts();
    foreach ($parentPosts as $parent):
        ?>
        <p>Response to:<a href="<?= $this->url('posts', ['action' => 'view', 'id' => $parent->getId()]); ?>">
                <?= $this->escapeHtml($parent->getTitle()); ?>
            </a>   
        </p>
    <?php endforeach; 
    if(count($parentPosts)<1)
        echo '<p>Response to: None';
    ?>
    
    <p>    
        <?= substr(nl2br($this->escapeHtml($post->getContent())), 0, 500) ?> &hellip;
    </p>
    
    <?php 
    $files = $imageManager->getFirstSavedFiles($post);
    ?>
    
    <hr/>

    <?php if(count($files)==0): ?>

    <p>
      <i>There are no images to display.</i>
    </p>

    <?php else: ?>

    <div class="row">
      <div class="col-sm-6 col-md-12">

        <?php foreach($files as $file): ?>  
            <a target="_blank" href="<?= $file ?>" class="btn btn-default" role="button">             
                <img width="240" src="<?= $file ?>">    
            </a>
        <?php endforeach; ?>
      </div>
    </div>

    <?php endif; ?>

    <hr/>


    <?php endforeach; ?>

    <?= $this->paginationControl($posts,
                    'Sliding',
                    'application/partial/paginator', 
                    array('route' => 'blog')); ?>
    
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Popular Tags</h3>
            </div>
            <div class="panel-body">
                <?php foreach($this->tagCloud as $tagName=>$frequency): ?>
                
                <a href="<?= $this->url('blog', ['action'=>'index'],
                    ['query'=>['tag'=>$tagName]]); ?>">                   
        
                    <span style="font-size:<?= $this->escapeHtml(0.9+$frequency*3) ?>em">
                        <?= $this->escapeHtml($tagName); ?>
                    </span>
                
                </a>    
                    
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    
    <?php if($this->identity()!=null): ?>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">My Favorite Tags</h3>
            </div>
            <div class="panel-body">
                <?php foreach($this->myTagCloud as $tagName=>$frequency): ?>
                
                <a href="<?= $this->url('blog', ['action'=>'index'],
                    ['query'=>['tag'=>$tagName]]); ?>">                   
        
                    <span style="font-size:<?= $this->escapeHtml(0.9+$frequency*3) ?>em">
                        <?= $this->escapeHtml($tagName); ?>
                    </span>
                
                </a>    
                    
                <?php endforeach; ?>
            </div>
        </div>
    </div>

    <?php endif; ?>
    
    
</div>
