<?php
$this->headTitle($this->translate('Blog'));
$this->mainMenu()->setActiveItemId('blog');
$this->pageBreadcrumbs()->setItems([
            $this->translate('Home')=>$this->url('home'),
            $this->translate('Blog')=>$this->url('blog')
            ]);

$form = $this->form;
$form->setAttribute('action', $this->url('blog'));
$form->get('tags')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>$this->translate('comma, separated, list, of, tags'),
    'label'=>$this->translate('Tags') 
    ));
$form->get('country')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>$this->translate('Country Name'),
    'label'=>$this->translate('Country')  
    ));
$form->get('region')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>$this->translate('Region Name'),
    'label'=>$this->translate('Region')  
    ));
$form->get('city')->setAttributes(array(
    'class'=>'form-control', 
    'placeholder'=>$this->translate('City Name'),
    'label'=>$this->translate('City')
    ));
$form->get('submit')->setAttributes(['class'=>'btn btn-primary', 
    'value'=>$this->translate('Submit')]);
$form->prepare();
?>



<div class="row">
    <div class="col-md-6">
        <?php echo $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('tags')); ?>
            <?php echo $this->formElement($form->get('tags')); ?>
            <?php echo $this->formElementErrors($form->get('tags')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('country')); ?>
            <?php echo $this->formElement($form->get('country')); ?>
            <?php echo $this->formElementErrors($form->get('country')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('region')); ?>
            <?php echo $this->formElement($form->get('region')); ?>
            <?php echo $this->formElementErrors($form->get('region')); ?>                  
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('city')); ?>
            <?php echo $this->formElement($form->get('city')); ?>
            <?php echo $this->formElementErrors($form->get('city')); ?>                  
        </div>
                
        <?php echo $this->formElement($form->get('csrf')); ?>
        
        <?php echo $this->formElement($form->get('submit')); ?>
        
        <?php echo $this->form()->closeTag(); ?>
    </div>    
</div> 

<?php 

if(
        $form->get('tags')->getValue() == '' &&
        $form->get('country')->getValue() == '' &&
        $form->get('region')->getValue() == '' &&
        $form->get('city')->getValue() == '' &&
        $tagFilter == '' &&
        $userFilter == '' 
  ): 
     
?>

<h1><?= $this->translate('All Posts') ?></h1>
    
<?php endif; ?>

<div class="row">
    
    <div class="col-md-8">

    <?php foreach($posts as $post): ?>
        
    <h3>
        <a href="<?= $this->url('posts', ['action'=>'view', 'id'=>$post->getId()]); ?>">
            <?= $this->escapeHtml($post->getTitle()); ?>
        </a>    
    </h3>
        
    <?php

    $time = strtotime($post->getDateCreated());
    $day = date('j', $time);
    $month = date('F', $time);
    $translatedMonth = $this->translate($month);
    $year = date('Y', $time);
    $date = "$day $translatedMonth $year"

    ?>
    
    <p>
        <?= $this->translate('Published:') ?> <?= $this->escapeHtml($date); ?> 
        | <?= $this->translate('Tags:') ?> <?= $this->escapeHtml($postManager->convertTagsToString($post)); ?>   
    </p> 
    
    <?php
        
    $country = $post->getGeography()->getCountryName();
    $translatedCountry = $this->translate($country);
    $region = $post->getGeography()->getRegion();
    $translatedRegion = $this->translate($region);
    $city = $post->getGeography()->getCity();
    $translatedCity = $this->translate($city);

    ?>
    
    <p>
        <?= $this->translate('Country:') ?> <?= $this->escapeHtml($translatedCountry); ?> 
        | <?= $this->translate('Region:') ?> <?= $this->escapeHtml($translatedRegion); ?>  
        | <?= $this->translate('City:') ?> <?= $this->escapeHtml($translatedCity); ?>  
    </p>  
    
    <p>
    <?= $this->translate('Author:') ?> <a href="<?= $this->url('blog', ['action'=>'index', 'user'=>$post->getUser()->getId()]); ?>">                   
        
                    <span >
                        <?= $this->escapeHtml($post->getUser()->getFullName()); ?> 
                    </span>
                
                </a>     
</p> 
        
    <p class="responses-header">
        <?= $this->escapeHtml($postManager->getResponseCountStr($post)); ?> | 
        <a href="<?= $this->url('posts', ['action'=>'add'], ['query' => 
                    ['id' => $post->getId()]]); ?>">
            <?= $this->translate('Add new response') ?>
        </a>
    </p>
    
    <?php
    $parentPosts = $post->getParentPosts();
    foreach ($parentPosts as $parent):
        ?>
        <p>Response to:<a href="<?= $this->url('posts', ['action' => 'view', 'id' => $parent->getId()]); ?>">
                <?= $this->escapeHtml($parent->getTitle()); ?>
            </a>   
        </p>
    <?php endforeach; 
    if(count($parentPosts)<1)
        echo $this->translate('<p>Response to: None');
    ?>
    
    <p>    
        <?= substr(nl2br($this->escapeHtml($post->getContent())), 0, 500) ?> &hellip;
    </p>
    
    <?php 
    $files = $imageManager->getFirstSavedFiles($post);
    ?>
    
    <hr/>

    <?php if(count($files)==0): ?>

    <p>
      <i><?= $this->translate('There are no images to display.') ?></i>
    </p>

    <?php else: ?>

    <div class="row">
      <div class="col-sm-6 col-md-12">

        <?php foreach($files as $file): ?>  
            <a target="_blank" href="<?= $file ?>" class="btn btn-default" role="button">             
                <img width="240" src="<?= $file ?>">    
            </a>
        <?php endforeach; ?>
      </div>
    </div>

    <?php endif; ?>

    <hr/>


    <?php endforeach; ?>

    <?= $this->paginationControl($posts,
                    'Sliding',
                    'application/partial/paginator', 
                    array('route' => 'blog')); ?>
    
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('Popular Tags') ?></h3>
            </div>
            <div class="panel-body">
                <?php foreach($this->tagCloud as $tagName=>$frequency): ?>
                
                <a href="<?= $this->url('blog', ['action'=>'index'],
                    ['query'=>['tag'=>$tagName]]); ?>">                   
        
                    <span style="font-size:<?= $this->escapeHtml(0.9+$frequency*3) ?>em">
                        <?= $this->escapeHtml($tagName); ?>
                    </span>
                
                </a>    
                    
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    
    <?php if($this->identity()!=null): ?>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('My Favorite Tags') ?></h3>
            </div>
            <div class="panel-body">
                <?php foreach($this->myTagCloud as $tagName=>$frequency): ?>
                
                <a href="<?= $this->url('blog', ['action'=>'index'],
                    ['query'=>['tag'=>$tagName]]); ?>">                   
        
                    <span style="font-size:<?= $this->escapeHtml(0.9+$frequency*3) ?>em">
                        <?= $this->escapeHtml($tagName); ?>
                    </span>
                
                </a>    
                    
                <?php endforeach; ?>
            </div>
        </div>
    </div>

    <?php endif; ?>
    
    
</div>
