<?php
$this->headTitle('Blog');
$this->mainMenu()->setActiveItemId('blog');
$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Blog'=>$this->url('blog')
            ]);
?>

<h1>All Posts</h1>

<div class="row">
    
    <div class="col-md-8">

    <?php foreach($posts as $post): ?>
        
    <h3>
        <a href="<?= $this->url('posts', ['action'=>'view', 'id'=>$post->getId()]); ?>">
            <?= $this->escapeHtml($post->getTitle()); ?>
        </a>    
    </h3>
    
    <p>
        Published: <?= $this->escapeHtml(date('jS \of F Y', strtotime($post->getDateCreated()))); ?> 
        | Tags: <?= $this->escapeHtml($postManager->convertTagsToString($post)); ?>   
    </p>    
        
    <p class="responses-header">
        <?= $this->escapeHtml($postManager->getResponseCountStr($post)); ?> | 
        <a href="<?= $this->url('posts', ['action'=>'add'], ['query' => 
                    ['id' => $post->getId()]]); ?>">
            Add new response
        </a>
    </p>
    
    <?php
    $parentPosts = $post->getParentPosts();
    foreach ($parentPosts as $parent):
        ?>
        <p>Response to:<a href="<?= $this->url('posts', ['action' => 'view', 'id' => $parent->getId()]); ?>">
                <?= $this->escapeHtml($parent->getTitle()); ?>
            </a>   
        </p>
    <?php endforeach; 
    if(count($parentPosts)<1)
        echo '<p>Response to: None';
    ?>
    
    <p>    
        <?= substr(nl2br($this->escapeHtml($post->getContent())), 0, 500) ?> &hellip;
    </p>
    
    <?php 
    $files = $imageManager->getFirstSavedFiles($post->getId());
    ?>
    
    <hr/>

    <?php if(count($files)==0): ?>

    <p>
      <i>There are no images to display.</i>
    </p>

    <?php else: ?>

    <div class="row">
      <div class="col-sm-6 col-md-12">

        <?php foreach($files as $file): ?>  
            <a target="_blank" href="<?= $this->url('images', ['action' => 'file'], 
            ['query' => ['name' => $file, 'id' => $post->getId(), 
            'loc' => 'perm']]); ?>" class="btn btn-default" role="button"> 

                <img src="<?= $this->url('images', ['action' => 'file'], ['query' => 
                ['name' => $file, 'id' => $post->getId(), 'loc' => 'perm', 
                'thumbnail' => true]]); ?>">

            </a>
        <?php endforeach; ?>
      </div>
    </div>

    <?php endif; ?>

    <hr/>


    <?php endforeach; ?>

    <?= $this->paginationControl($posts,
                    'Sliding',
                    'application/partial/paginator', 
                    array('route' => 'blog')); ?>
    
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Popular Tags</h3>
            </div>
            <div class="panel-body">
                <?php foreach($this->tagCloud as $tagName=>$frequency): ?>
                
                <a href="<?= $this->url('blog', ['action'=>'index'],
                    ['query'=>['tag'=>$tagName]]); ?>">                   
        
                    <span style="font-size:<?= $this->escapeHtml(0.9+$frequency*3) ?>em">
                        <?= $this->escapeHtml($tagName); ?>
                    </span>
                
                </a>    
                    
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    
    <?php if($this->identity()!=null): ?>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">My Tags</h3>
            </div>
            <div class="panel-body">
                <?php foreach($this->myTagCloud as $tagName=>$frequency): ?>
                
                <a href="<?= $this->url('blog', ['action'=>'index'],
                    ['query'=>['tag'=>$tagName]]); ?>">                   
        
                    <span style="font-size:<?= $this->escapeHtml(0.9+$frequency*3) ?>em">
                        <?= $this->escapeHtml($tagName); ?>
                    </span>
                
                </a>    
                    
                <?php endforeach; ?>
            </div>
        </div>
    </div>

    <?php endif; ?>
    
    
</div>
