<?= $this->doctype() ?>

<html lang="en">
    <head>
        
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-116658932-1"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'UA-116658932-1');
        </script>
        
        <meta charset="utf-8">
        <?= $this->headTitle('Policy Bubble')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <!-- Navigation bar -->
        <?php
        // Check if the activeMenuItemId passed to layout view model
        // and if so, use it for setting active navbar item.
        if (isset($activeMenuItemId)) {
            $this->mainMenu()->setActiveItemId($activeMenuItemId);
        }
        // Render the navbar
        echo $this->mainMenu()->render();
        ?>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- Breadcrumbs -->
                    <?= $this->pageBreadcrumbs()->render(); ?>
                </div>
            </div>
            <?= $this->content ?>
            <hr>
            <footer>
                <span>&copy; <?= date('Y') ?> <?= $this->translate('by') ?> David's Web Sites. 
                    <?= $this->translate('All rights reserved.') ?></span> |
                <a href="<?= $this->url('privacypolicy') ?>" ><?= $this->translate('Privacy Policy') ?> </a> |
                <a href="<?= $this->url('disclosurepolicy') ?>" ><?= $this->translate('Disclosure Policy') ?> </a> |
                <a href="<?= $this->url('termsofservice') ?>" ><?= $this->translate('Terms of Service') ?> </a> |
                <iframe src="https://ghbtns.com/github-btn.html?user=david-garcia-nete&repo=policy-bubble&type=fork&count=true" 
                        frameborder="0" scrolling="0" width="170px" height="18px"></iframe>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
