<?php
$this->headTitle('About');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home'),
            'About'=>$this->url('about')
            ));
?>

<h1>About</h1>

<h3>Overview</h3>

<p>
    Policy Bubble aims to collect data about user's opinions.  Survey data is 
    limited in what it can provide about public opinion because question are close ended.
    Policy Bubble lets you share first hand your experiences with government, business or anything
    else on your mind using text, photos, video and audio.
    
    As the database expands analysis is performed using data visualization thus informing political choices.
    
</p>

<h3>Usage</h3>

<p>
  After joining Policy Bubble you will have a post administration page for creating, editing and deleting posts.
  You can filter the blog on topics that interest you.  There is an analysis page that policy makers and constituents
  can use to improve how laws are made. 
</p>


<h3>Post Management Page</h3>
 <img width="100%" src="img/about/post admin screen v2.png">
<h3>Add/Edit Post Step 1</h3>
 <img width="100%" src="img/about/add post step 1 v2.png">
<h3>Add/Edit Post Step 2</h3>
 <img width="100%" src="img/about/add post step 2 v2.png">
<h3>Add/Edit Post Step 3</h3>
 <img width="100%" src="img/about/add post step 3 v2.png">
<h3>Add/Edit Post Step 4</h3>
 <img width="100%" src="img/about/add post step 4 v2.png">
<h3>User Settings</h3>

<p>
    Users can update their name, email and password and delete their account.
</p>

 <img width="100%" src="img/about/user settings v3.png">

<!--<h3>In Development</h3>

<ul>
  <li>Demographics form on user settings page.</li>
  <li>Delete account form on user settings page.</li>
  <li>Feeling/emotion field on post form step one.</li>
  <li>Save membership level to post.</li>
  <li>Citations field on post form step one.</li>
  <li>Save media file counts to post in database.</li>
  <li>Estimated cost field on post form step one.</li>
  <li>Ethical field on post form step one.</li>
  <li>Reports on analysis page.</li>
  
</ul>-->