<?php
$this->headTitle('About');

$this->mainMenu()->setActiveItemId('about');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home'),
            'About'=>$this->url('about')
            ));
?>

<h1>About</h1>

<h3>Overview</h3>

<p>
    Policy Bubble aims to collect data about user's opinions.  Survey data is 
    limited in what it can provide about public opinion because question are close ended.
    Policy Bubble lets you share first hand your experiences with government, business or anything
    else on your mind using text, photos, video and audio.
    
    As the database expands analysis is performed using data visualization thus informing political choices.
    
</p>

<h3>Usage</h3>

<p>
  After joining Policy Bubble you will have a post administration page for creating, editing and deleting posts.
  You can filter the blog on topics that interest you.  There is an analysis page that policy makers and constituents
  can use to improve how laws are made. 
</p>