<?php
use User\Entity\User;
use Application\Entity\Post;

$this->headTitle('Analysis');

$this->mainMenu()->setActiveItemId('analysis');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home'),
            'Analysis'=>$this->url('analysis')
            ));
?>

<h1>Analysis</h1>

<h3>Number of Users</h3>

<h4>
<?php
   echo count( $this->entityManager->getRepository(User::class)
                    ->findBy(array('status' => User::STATUS_ACTIVE)));
?>    
</h4>

<h3>Number of Posts</h3>

<h4>
<?php
    echo count( $this->entityManager->getRepository(Post::class)
                    ->findBy(array('status' => Post::STATUS_PUBLISHED)));
?> 
</h4>

<h3>Number of Responses</h3>

<h4>
<?php
    echo $this->entityManager->getRepository(Post::class)
                    ->findPublishedChildPostsCount();
?> 
</h4>

<h3>Number of Tags</h3>

<h4>
<?php
    echo count( $this->entityManager->getRepository(Post::class)
                    ->findPublishedTags());
?> 
</h4>

<h3>Number of Countries</h3>

<h4>
<?php
    echo count($this->entityManager->getRepository(Post::class)
                    ->findDistinctPublishedGeography('countryName'));
?> 
</h4>

<h3>Number of Regions</h3>

<h4>
<?php
    echo count($this->entityManager->getRepository(Post::class)
                    ->findDistinctPublishedGeography('region'));
?> 
</h4>

<h3>Number of Cities</h3>

<h4>
<?php
    echo count($this->entityManager->getRepository(Post::class)
                    ->findDistinctPublishedGeography('city'));
?> 
</h4>


<!--<h3>
 
<a href="<?= $this->url('analysis', ['action'=>'popularTags']); ?>" target="_blank"> Popular Tags</a>

</h3>

-->
<!--
<br>

<h4>
 
<a href="https://github.com/d3/d3/wiki/Gallery" target="_blank"> Data visualizations will be coming soon.</a>

</h4>-->

