<?php
use User\Entity\User;
use Application\Entity\Post;
use Application\Entity\Tag;

$this->headTitle('Analysis');

$this->mainMenu()->setActiveItemId('analysis');

$this->pageBreadcrumbs()->setItems(array(
            'Home'=>$this->url('home'),
            'Analysis'=>$this->url('analysis')
            ));
?>

<h1>Analysis</h1>

<h3>Number of Users</h3>

<h4>
<?php
   echo count( $this->entityManager->getRepository(User::class)
                    ->findAll());
?>    
</h4>

<h3>Number of Posts</h3>

<h4>
<?php
    echo count( $this->entityManager->getRepository(Post::class)
                    ->findAll());
?> 
</h4>

<h3>Number of Tags</h3>

<h4>
<?php
    echo count( $this->entityManager->getRepository(Tag::class)
                    ->findAll());
?> 
</h4>


<h3>
 
<a href="https://bl.ocks.org/mbostock/4063269" target="_blank"> Popular Tags</a>

</h3>

<br>

<h4>
 
<a href="https://github.com/d3/d3/wiki/Gallery" target="_blank"> More data visualizations will be coming soon.</a>

</h4>

