<div class="jumbotron">
    <h1>Welcome to <span class= "pb-blue">Policy Bubble</span></h1>

    <p>
        This is a place where policy can be improved.
    </p>

    <span><a class="btn btn-info btn-lg" href="/register" target="_blank">Register &raquo;</a></span>
    <span><a class="btn btn-info btn-lg" href="/login" target="_blank">Log In &raquo;</a></span>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Blogs</h3>
            </div>
            <div class="panel-body">
                <p>
                    Write about policies affecting your area.
                </p>

                <span><a class="btn btn-info pull-right" href="/blogs" target="_blank">Read &raquo;</a></span>

            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Photos</h3>
            </div>
            <div class="panel-body">
                <p>
                    Show how policies are affecting your area.
                </p>

                <p><a class="btn btn-info pull-right" href="/photos" target="_blank">See &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Feedback</h3>
            </div>
            <div class="panel-body">
                <p>
                    Let us know what you think.
                </p>

                <p><a class="btn btn-info pull-right" href="/feedback" target="_blank">Talk &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
