<?php
$this->mainMenu()->setActiveItemId('home');

$form->get('language')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-info', 
    'value'=>$this->translate('Submit')]);

$form->prepare();

?>

<?php if($this->identity()==null): ?>

<div class="row">
    <div class="col-md-9">
        
    </div>
    
    <div class="col-md-2">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formElement($form->get('language')); ?>
            <?= $this->formElementErrors($form->get('language')); ?>                              
        </div>
        
    </div>
    
    <div class="col-md-1">

            <div class="form-group">
            <?= $this->formElement($form->get('submit')); ?>
            </div>

            <?= $this->formElement($form->get('csrf')); ?>

            <?= $this->form()->closeTag(); ?>
        </div>        
</div>   

<?php endif; ?>

<div class="jumbotron">
    <h1> <?= $this->translate('Welcome to') ?> <span class= "pb-blue">Policy Bubble</span></h1>

    <p>
        <?= $this->translate('This is a place where policy can be improved.') ?> 
    </p>

</div>

<div class="row">
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('About') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <?= $this->translate('Learn about Policy Bubble.') ?>
                </p>

                <p>
                    <a class="btn btn-info pull-right" 
                       href="<?php echo $this->url('about'); ?>"><?php echo 
                       $this->translate('Learn') ?> &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('Feedback') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <?= $this->translate('Let us know what you think.') ?>
                </p>

                <p>
                    <a class="btn btn-info pull-right" 
                       href="<?php echo $this->url('contactus'); ?>">
                           <?= $this->translate('Talk') ?> &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('Blog') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <?= $this->translate('Read about policies affecting your area.') ?>
                </p>

                <p>
                    <a class="btn btn-info pull-right" 
                       href="<?php echo $this->url('blog'); ?>" >
                           <?= $this->translate('Read') ?> &raquo;
                    </a>
                </p>

            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('Posts') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <?= $this->translate('Tell how policies are affecting your area.') ?>
                </p>

                <p>
                    <a class="btn btn-info pull-right" 
                       href="<?php echo $this->url('posts'); ?>">
                           <?= $this->translate('Tell') ?> &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('Analysis') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <?= $this->translate('See how policies are affecting your area.') ?>
                </p>

                <p>
                    <a class="btn btn-info pull-right" 
                       href="<?php echo $this->url('analysis'); ?>">
                           <?= $this->translate('See') ?> &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>
    
</div>
