<?php

$this->headTitle($this->translate('Contact Us'));

$this->mainMenu()->setActiveItemId('contactUs');

$this->pageBreadcrumbs()->setItems(array(
            $this->translate('Home')=>$this->url('home'),
            $this->translate('Contact Us')=>$this->url('contactus')
            ));

?>

<h1><?= $this->translate('Error Sending Email!') ?></h1>

<p>
    <div class="alert alert-warning">
        <?= $this->translate('Sorry, but we had an unexpected problem when trying to deliver your message.  Please try again later.') ?> 
    </div>
</p>