<?php

$this->headTitle($this->translate('Contact Us'));

$this->mainMenu()->setActiveItemId('contactUs');

$this->pageBreadcrumbs()->setItems(array(
            $this->translate('Home')=>$this->url('home'),
            $this->translate('Contact Us')=>$this->url('contactus')
            ));

?>

<h1><?= $this->translate('Thank You!') ?></h1>

<p>
    <div class="alert alert-success">
        <?= $this->translate('We will respond to the E-mail address you have provided.') ?> 
    </div>
</p>
